import type { FlowRooms } from '../flow-live.js';
import type { IntegrationMonitor } from '../integrations.js';
import type { OidcSettings } from '../oidc.js';
import type { OpenRouterModels } from '../openrouter-models.js';
import type { ProjectCeiling } from '../project.js';
import type { TaskRooms } from '../task-live.js';
/** Captured server state and shared guards. Getters preserve live state across requests. */
import { type IncomingMessage,type ServerResponse } from "node:http";
import { type AssignmentSnapshot } from '../assignment.js';
import { type BrowserPhoneCard,type BrowserUpdates } from '../browser-workspace.js';
import { CodingWorkspace } from '../coding-workspace.js';
import { type FormFieldOf,type FormView } from "../contracts/console-api.js";
import type { DemoLead } from "../demo.js";
import { type FirstRunStep,type FirstTaskSuggestion } from "../first-run.js";
import { type GoogleVisit } from "../google-mail.js";
import { type ConnectVisit } from "../mcp-connect.js";
import { type CatalogSeams } from "../model-catalog.js";
import { type FailureExplanation } from '../needs-you.js';
import { type OidcClaims,type OidcProvider,type OidcVisit } from "../oidc.js";
import { type Principal } from "../operate-remote.js";
import { type VerifiedApprover } from "../principal.js";
import { type ProjectSettingsView } from "../project-delete-ui.js";
import { type ProviderConnection } from "../provider-connection.js";
import { type ProviderId } from "../provider.js";
import {
authenticateApprover as checkApproverPassword,
type Scope
} from "../scope.js";
import { SourceBudget } from "../sign-in-guard.js";
import type { CoordinatorProposal,DirectChatProviderId,LeadMessage,LeadProposal,LeadTurn,PlanRevision,TaskFamily,TaskRef } from "../store.js";
import {
type Decision,
type LeadAsk,type LeadThreadScope,
type Run,
type Store,
type Task,
type TaskState
} from "../store.js";
import type { TeamChatProviderResolver } from '../team-chat-authorization.js';
import type { TeamResponse } from '../team-contract.js';
import { createTeamRuntime } from '../team-runtime.js';
import { type ToolsView } from "../tools-ui.js";
import {
type ReviewFacts
} from "../workspace-ui.js";
import { WorktreePool } from "../worktree.js";
import { PersistentSessions,taskBody,type ChatEnablement,type Chrome,type LiveTurn,type PlanContractView,type PlanRevisionLedgerView,type ProjectPeek,type ReplacedThread,type ResultDetail,type RevisionDocView,type RevisionView,type RouteView,type Screen,type ServeOptions,type Session,type SsoIntent,type TaskChatFocus,type Who } from "./shared.js";

export interface ServerRuntime {
  codingActorAllowed: (actor: { name: string; generation: number; }) => boolean;
  coding: CodingWorkspace | null;
  codingProjectAllowed: (repo: string) => boolean;
  store: Store;
  sendScreen: (response: ServerResponse, status: number, s: Screen) => void;
  chromeFor: (project: string | null, active: Chrome["active"], listPane?: string, scope?: Chrome["scope"]) => Chrome;
  visible: (repo: string | null) => boolean;
  managedRepos: () => string[];
  codingProblem: string | undefined;
  unscopedMode: boolean;
  admissionList: () => string[] | null;
  routeViewOf: (taskId: string, ref: TaskRef | null, scope: Scope | null, now: Date, who: Who) => RouteView | null;
  workAccess: () => { principal: "operator"; repos: string[] | null; includeUnplaced: boolean; viewer: string | null; };
  evidenceRoot: string;
  firstRunStepsNow: (now: Date) => FirstRunStep[] | null;
  restricted: () => boolean;
  revisionDocOf: (row: PlanRevision) => RevisionDocView | null;
  familyOf: (taskId: string) => TaskFamily | null;
  failureOf: (runs: readonly Run[], assignment: AssignmentSnapshot | null, readLog?: boolean) => FailureExplanation;
  dockedConversation: (who: Who, focusTask: TaskChatFocus | null, chatProject: string | null, now: Date, back: string, resultRunId?: number | null) => import("../browser-workspace.js").BrowserConversation | null;
  planViewOf: (taskRef: number) => { document: string; sha256: string; run: number; } | null;
  mintApprovalNonce: (name: string, taskId: string, digest: string) => string;
  planContractViewOf: (taskRef: number, scope: Scope | null) => PlanContractView | null;
  familiesInView: (project: string | null, options?: Parameters<Store["taskFamiliesAdmitted"]>[2]) => TaskFamily[];
  runIsTaskResult: (run: Pick<Run, "role" | "finishedAt">) => boolean;
  explainAttempt: (run: Run, receipt: AssignmentSnapshot["receipt"] | null, readLog?: boolean) => FailureExplanation;
  taskChatFocus: (taskId: string | null, now: Date, who?: Who, options?: { mintNonce?: boolean; }) => TaskChatFocus | null;
  familyTasksInView: (project: string | null, state?: TaskState, limit?: number) => (Task & { repo: string | null; })[];
  clock: () => Date;
  taskRooms: TaskRooms;
  identify: (request: IncomingMessage, touch?: boolean, limited?: boolean, refusedToken?: { principal?: Principal; }) => Who | null;
  liveCeiling: () => { repos: string[]; roots: readonly string[]; };
  taskScreen: (response: ServerResponse, who: Who, taskId: string, problem: string | null, status: number, scopeDraft?: URLSearchParams, cancelDraft?: string, editPlan?: boolean) => void;
  runVisible: (run: Run) => boolean;
  runIsLive: (run: Pick<Run, "outcome" | "leaseId" | "taskRef">) => boolean;
  options: ServeOptions;
  reviewFactsFor: (runId: number) => ReviewFacts | null;
  resultDetailOf: (run: Run, who: Who, now: Date) => ResultDetail;
  taskRepoOf: (taskRef: number) => string | null;
  ceiling: ProjectCeiling;
  taskViewData: (taskId: string, who: Who, problem: string | null, render?: { mintNonce?: boolean; }) => Parameters<typeof taskBody>[0] | null;
  consoleProjects: () => string[];
  flowRooms: FlowRooms;
  providerHome: string;
  toolHome: string;
  leadPrincipal: (who: Who & { via: "cookie"; }) => VerifiedApprover | null;
  chatScopeOf: (focusTask: TaskChatFocus | null, chatProject: string | null) => LeadThreadScope;
  liveTurns: Map<number, LiveTurn>;
  chatStreams: Set<ServerResponse<IncomingMessage>>;
  leadConversationRows: (who: Who & { via: "cookie"; }, principal: VerifiedApprover, focusTask: TaskChatFocus | null, now: Date, chatProject?: string | null) => { messages: LeadMessage[]; proposals: LeadProposal[]; decisions: Map<number, Decision>; coordinatorProposals: CoordinatorProposal[]; pending: LeadTurn | null; recent: LeadTurn[]; ask: LeadAsk | null; asks: Map<number, LeadAsk>; previous: ReplacedThread | null; };
  demoLeadHere: () => DemoLead | null;
  teamBrowserReply: (reply: TeamResponse, actor: { name: string; generation: number; }, csrf: string) => TeamResponse;
  team: ReturnType<typeof createTeamRuntime>;
  teamChatProvider: TeamChatProviderResolver;
  pullRequestTargetOf: (runId: number) => string | null;
  chatEnablement: () => ChatEnablement;
  startLeadConversation: (who: Who & { via: "cookie"; }, principal: VerifiedApprover, enabled: Extract<ChatEnablement, { ok: true; }>, ceilingUsd: number, follow: boolean, now: Date) => number;
  projectFamilyPeek: (repo: string, now: Date) => ProjectPeek;
  needsYouBadge: (project: string | null) => { count: number; saturated: boolean; };
  liveRefreshSeconds: () => number;
  chatKeyFor: (provider: DirectChatProviderId) => { key: string; source: "environment" | "stored"; } | null;
  chatCatalog: () => Promise<import("../converse.js").CatalogModel[] | null>;
  leadRecheckedAt: number;
  checkLocalAgents: (fresh?: boolean) => Promise<void>;
  localSignIn: { at: number; signedIn: boolean; states: Record<"claude" | "codex", ProviderConnection["state"] | "unverified">; } | null;
  agentSignInCommand: () => string;
  connectionCheck: (provider: ProviderId, fresh?: boolean) => Promise<ProviderConnection>;
  modelCatalog: (key: string | null, refresh?: boolean) => Promise<OpenRouterModels>;
  modelSeams: CatalogSeams;
  toolsViewOf: (repo: string, codex: unknown[] | null, kit?: string | null, wanted?: string | null) => ToolsView;
  codexServers: (repo: string) => Promise<unknown[] | null>;
  projectViewOf: (repo: string, who: Who) => ProjectSettingsView;
  sessions: PersistentSessions;
  integrations: IntegrationMonitor;
  consoleOrigin: (host: string | undefined) => string | null;
  storagePool: (databaseFile: string) => WorktreePool;
  ssoSettings: () => OidcSettings | null;
  leadWords: () => string | null;
  settingsUpdates: (actor: string, csrf: string) => BrowserUpdates | null;
  phoneSetup: (who: Who) => BrowserPhoneCard | undefined;
  authenticateApprover: (who: Who, token: string, repo?: string | null) => ReturnType<typeof checkApproverPassword>;
  projectOf: (who: Who, request: IncomingMessage) => string | null | undefined;
  bustBadge: () => void;
  revisionDestination: (child: string, back: string) => string;
  deletedRepos: Set<string>;
  lookupSession: (candidate: string, touch?: boolean) => Session | null;
  authorizeMutation: (request: IncomingMessage, who: Who, body: FormView<FormFieldOf<"mutationGuard">>) => { status: number; message: string; } | null;
  leadSaid: Map<string, { turn: number | null; message: string; }>;
  armTaskResume: (response: ServerResponse, who: Who, taskId: string, named: string, returnTo: "chat" | "task", now: Date) => void;
  chatFetcher: { (input: RequestInfo | URL, init?: RequestInit): Promise<Response>; (input: string | URL | Request, init?: RequestInit): Promise<Response>; };
  chatCeilingDigest: (repos?: readonly string[]) => string;
  consumeApprovalNonce: (nonce: string, name: string, taskId: string, digest: string) => boolean;
  recordSignIn: (actor: string, action: string, outcome: string, detail?: string | null) => void;
  ssoProvider: { issuer: string; provider: OidcProvider; at: number; } | null;
  providerFor: (issuer: string) => Promise<{ ok: true; provider: OidcProvider; } | { ok: false; said: string; }>;
  connectVisits: Map<string, ConnectVisit>;
  defaultProject: string | null;
  googleVisits: Map<string, GoogleVisit>;
  setupAttemptsLeft: number;
  ssoOffer: () => { label: string; operatorsOnly: boolean; } | null;
  signInLinks: Map<string, { account: string; expires: number; }>;
  linkKey: (code: string) => string;
  fromThisComputer: (request: IncomingMessage) => boolean;
  passwordAllowed: (name: string) => boolean;
  arrival: (request: IncomingMessage) => { agent: string | null; address: string; };
  cookieSecure: "" | "; Secure";
  ssoVisits: Map<string, { visit: OidcVisit; provider: OidcProvider; redirect: string; intent: SsoIntent; returnTo: string; expires: number; }>;
  ssoHandoffs: Map<string, { claims: OidcClaims; issuer: string; intent: SsoIntent; returnTo: string; expires: number; }>;
  joinSourceOf: (request: IncomingMessage) => string;
  signInBudget: SourceBudget;
  signInActor: (name: string | null) => string;
  minutesWords: (ms: number) => string;
  joinGlobal: { tokens: number; refilledAt: number; };
  joinBySource: Map<string, { tokens: number; refilledAt: number; }>;
  catalogCache: { at: number; models: import("../converse.js").CatalogModel[]; } | null;
  CHAT_CANDIDATE_TTL_MS: number;
  CHAT_CANDIDATES_PER_APPROVER: 9;
  peekSay: (message: string, final?: boolean) => string;
  peekCache: Map<string, { fragment: string; at: number; }>;
  PEEK_CACHE_TTL_MS: 10000;
  peekCacheBytes: number;
  peekInFlight: Map<string, Promise<string>>;
  PEEK_GLOBAL_INFLIGHT: 4;
  peekBySession: Map<string, number>;
  PEEK_SESSION_INFLIGHT: 2;
  peekName: (path: string) => string;
  PEEK_FRAGMENT_BYTES: number;
  peekEvict: () => void;
  allowedHost: (host: string | undefined) => boolean;
  revisionViewOf: (ref: ReturnType<Store["lookupRef"]>) => RevisionView | null;
  revisionLedgerOf: (taskRef: number) => PlanRevisionLedgerView;
  firstTasks: Map<string, { until: number; found: FirstTaskSuggestion[] | null; reading: boolean; }>;
}
