/**
 * Read-only copies of what the coding catalog saved before the Zod revamp (0.9.36): a managed context capture, two
 * `coding_session` rows and a `coding_handoff` receipt with its scope seal. Generated by the 0.9.36 code in a scratch
 * project; nothing personal is in them. Never regenerate them with newer code: they are the old bytes to keep reading.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("./fixtures/coding/", import.meta.url));
const read = (name: string): string => readFileSync(`${root}${name}`, "utf8");

/** The capture as `JSON.stringify(prepareCodingContext(...))` wrote it. */
export const savedContext: string = read("context.json").trimEnd();

export type SavedSessionRow = { id: string; owner: string; generation: number; repo: string; document: string; revision: number };
/** An interrupted session with a context, and a closed one whose startup was never confirmed. */
export const savedSessionRows: readonly SavedSessionRow[] = (JSON.parse(read("sessions.json")) as { rows: SavedSessionRow[] }).rows;

export type SavedHandoff = {
  handoff: { id: string; payload: string; sha: string; created_at: string };
  scope: { id: string; payload: string; sha: string };
  scopeDigest: string;
};
export const savedHandoff: SavedHandoff = JSON.parse(read("handoff.json")) as SavedHandoff;
