import { STALE_KNOWLEDGE, type KnowledgeDraft, type KnowledgeSelection, type KnowledgeView } from './project-knowledge.js';
import { html, postForm, type Html } from './html.js';
// Hidden fields as they always were: a missing value is an empty field.
const fields = (data:Record<string,unknown>):Record<string,string> => Object.fromEntries(Object.entries(data).map(([k,v])=>[k,String(v ?? '')]));
export const KNOWLEDGE_CSS = `.knowledge{max-width:780px;min-width:0;overflow-wrap:anywhere}.knowledge .card{padding:20px;min-width:0;margin:16px 0}.knowledge h2{margin:0 0 12px}.knowledge form{display:grid;gap:12px;margin:0}.knowledge label{display:grid;gap:6px}.knowledge textarea,.knowledge input,.knowledge select{box-sizing:border-box;width:100%;min-width:0;max-width:100%}.knowledge textarea{resize:vertical;min-height:110px}.knowledge button,.knowledge summary,.knowledge .button-link{min-height:44px}.knowledge button{justify-self:start;white-space:nowrap}.knowledge summary{padding:12px 0;cursor:pointer}.knowledge pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}.knowledge .knowledge-actions{display:flex;gap:12px;flex-wrap:wrap}.knowledge .meta{font-size:.86rem}.knowledge .knowledge-source{display:block}.knowledge details+details{border-top:1px solid var(--so-line)}.memory-stats{display:flex;flex-wrap:wrap;gap:.4rem}.memory-stats span{padding:.15rem .55rem;border-radius:.375rem;background:var(--so-neutral-soft);color:var(--so-neutral-ink)}@media(max-width:600px){.knowledge .card{padding:16px}.knowledge h2{font-size:1.1rem}}`;
export function knowledgeHtml(view:KnowledgeView,csrf:string,canManage:boolean,draft?:KnowledgeDraft,error?:string):Html {
  const manage=canManage && !!csrf;
  const base={repo:view.repo,identity:view.identity,revision:view.revision};
  const form=(action:string,body:Html,extra:Record<string,unknown>={})=>postForm('/settings/knowledge/change',body,{hidden:fields({...base,action,...extra})});
  const referenceFields=(d:KnowledgeDraft)=>html`<label>Name<input name="title" maxlength="120" value="${d.title}" required></label><label>Reference text<textarea name="content" rows="5" maxlength="12000">${d.content}</textarea></label><details${d.path?html` open`:''}><summary>Use a project document</summary><label>Committed .md or .txt path<input name="path" value="${d.path}" placeholder="docs/design-guide.md"></label><p class="meta">Uses the committed file instead of the text above. Save again to refresh it.</p></details><button type="submit">Save reference</button>`;
  const refs=view.knowledge.references.map(ref=>html`<details class="card"${draft?.id===ref.id?html` open`:''}><summary><strong>${ref.title}</strong></summary>${ref.path?html`<span class="meta knowledge-source">${ref.path} · ${ref.sourceRevision?.slice(0,7)}</span>`:''}<pre>${ref.content}</pre>${manage?html`<details${draft?.id===ref.id?html` open`:''}><summary>Edit reference</summary>${form('save',referenceFields(draft?.id===ref.id?draft:{title:ref.title,content:ref.path?'':ref.content,path:ref.path??''}),{id:ref.id})}<details><summary>Remove reference</summary>${form('remove',html`<p>Remove from future tasks. Previous run context stays available.</p><button>Remove reference</button>`,{id:ref.id})}</details></details>`:''}</details>`);
  const history=view.history.map(h=>html`<li><a class="button-link" href="/settings/knowledge?repo=${encodeURIComponent(view.repo)}&version=${h.revision}">Version ${h.revision}</a> · ${h.actor} · ${h.at.slice(0,16).replace('T',' ')} UTC</li>`);
  if (view.stale) {
    // One notice, the saved knowledge on demand, one approver action. Editing waits until it is applied.
    const saved=view.stale.knowledge;
    const review=html`<details><summary>Review saved knowledge</summary><pre class="knowledge-instructions">${saved.instructions||'No project instructions.'}</pre>${saved.references.map(ref=>html`<details><summary>${ref.title}</summary><pre>${ref.content}</pre></details>`)}</details>`;
    return html`<section class="knowledge knowledge-library">${error?html`<p class="problem" role="alert">${error}</p>`:''}<section class="card knowledge-stale"><p role="status">${STALE_KNOWLEDGE}.</p>${review}${manage?form('apply',html`<button>Apply saved knowledge</button>`):''}</section></section>`;
  }
  const instructions = html`<pre class="knowledge-instructions">${view.knowledge.instructions||'No project instructions yet.'}</pre>`;
  const editor = manage ? html`<details class="knowledge-editor"${draft?.instructions!==undefined?html` open`:''}><summary>${view.knowledge.instructions?'Edit instructions':'Add instructions'}</summary>${form('instructions',html`<textarea aria-label="Project instructions" name="instructions" rows="5" maxlength="4000" placeholder="Goals, preferences, and what good work looks like…">${draft?.instructions??view.knowledge.instructions}</textarea><button>Save instructions</button>`)}</details>` : '';
  return html`<section class="knowledge knowledge-library">${error?html`<p class="problem" role="alert">${error}</p>`:''}<section class="knowledge-intro"><h2>Instructions</h2>${instructions}${editor}</section><section><h2>References</h2>${refs.length?refs:html`<p class="meta">Add a spec, design guide, or useful project document.</p>`}${manage?html`<details class="card"${draft?.title&&!draft.id?html` open`:''}><summary>Add reference</summary>${form('save',referenceFields(draft?.id?{}:draft??{}))}</details>`:''}</section>${history.length?html`<details><summary>Change history</summary><ol>${history}</ol></details>`:''}</section>`;
}
export function knowledgeContextHtml(snapshot:KnowledgeSelection|null):Html|'' {
  if (!snapshot) return '';
  return html`<details class="knowledge result-knowledge"><summary>Context used</summary><p class="meta">Project knowledge · version ${snapshot.revision}${snapshot.inheritedFrom===null?'':` · from run #${snapshot.inheritedFrom}`}</p>${snapshot.instructions?html`<details><summary>Instructions</summary><pre>${snapshot.instructions}</pre></details>`:html`<p>No project instructions were supplied.</p>`}${snapshot.references.map(r=>html`<details><summary>${r.title}</summary>${r.path?html`<p class="meta">${r.path} · ${r.sourceRevision}</p>`:''}<pre>${r.content}</pre></details>`)}${snapshot.omitted.length?html`<details><summary>Not included (${snapshot.omitted.length})</summary><ul>${snapshot.omitted.map(r=>html`<li>${r.title} — ${r.reason}</li>`)}</ul></details>`:''}</details>`;
}

// ---- project memory: decisions and search (2026-09-21) ----------------------------
import type { Decision, MemoryHit } from './project-memory.js';
export const MEMORY_INTRO = 'What the lead and crew read before they work. Every change keeps its history.';
export function decisionsHtml(repo: string, decisions: Decision[], csrf: string, canManage: boolean, draft?: { claim?: string; why?: string }, error?: string): Html {
  const manage = canManage && !!csrf;
  const base = { repo };
  const form = (action: string, body: Html, extra: Record<string, unknown> = {}) => postForm('/settings/knowledge/decision', body, { hidden: fields({ ...base, action, ...extra }) });
  const rows = decisions.map(d => html`<details class="card decision" id="decision-${d.id}"><summary><strong>${d.claim}</strong> <span class="meta">#${d.id} · ${d.decidedBy} · ${d.decidedAt.slice(0, 10)}</span></summary><p>${d.why}</p><p class="meta">${d.sourceKind}${d.sourceRef ? ` · ${d.sourceRef}` : ''}${d.supersedes === null ? '' : ` · replaces #${d.supersedes}`}</p>${manage ? form('retire', html`<label>Why it no longer holds<input name="reason" maxlength="500" required></label><button type="submit">Retire</button>`, { decision: d.id }) : ''}</details>`);
  const add = manage ? html`<details class="knowledge-editor"${draft?.claim !== undefined ? html` open` : ''}><summary>Record a decision</summary>${form('record', html`<label>The choice, in one sentence<input name="claim" maxlength="240" value="${draft?.claim}" required></label><label>Why<textarea name="why" rows="3" maxlength="2000" required>${draft?.why}</textarea></label><button type="submit">Record</button>`)}</details>` : '';
  return html`<section class="knowledge"><h2>Decisions</h2>${error ? html`<p class="problem" role="alert">${error}</p>` : ''}${rows.length ? rows : html`<p class="meta">No decisions yet. The lead suggests one when a conversation settles a choice.</p>`}${add}</section>`;
}
export function memorySearchHtml(repo: string, query: string, hits: MemoryHit[] | null): Html {
  const kind = (h: MemoryHit) => h.kind === 'decision' ? html`<a href="#decision-${h.ref}">decision #${h.ref}</a>` : h.kind === 'conversation' ? 'conversation' : h.kind;
  const results = hits === null ? '' : hits.length === 0 ? html`<p class="meta">Nothing in project memory matches.</p>` : html`<ul class="memory-hits">${hits.map(h => html`<li><strong>${kind(h)}</strong> · ${h.title}<br><span class="meta">${h.snippet}</span></li>`)}</ul>`;
  return html`<section class="knowledge memory-search"><form method="get" action="/settings/knowledge"><input type="hidden" name="repo" value="${repo}"><label>Search project memory<input name="memory" value="${query}" maxlength="300" placeholder="Search decisions, references, lessons…" type="search" autocomplete="off"></label><button type="submit">Search</button></form>${results}</section>`;
}
import type { MemoryProposal } from './memory-pass.js';
export function proposalsHtml(repo: string, proposals: MemoryProposal[], status: { surface: string; instructionBytes: number; budgetBytes: number; sessions: { total: number; analyzed: number; failed: number }; openGaps: number; pending: number } | null, csrf: string, canManage: boolean): Html {
  const manage = canManage && !!csrf;
  const line = status === null ? '' : html`<p class="meta memory-stats"><span>${status.sessions.analyzed}/${status.sessions.total} sessions read${status.sessions.failed ? ` · ${status.sessions.failed} failed` : ''}</span><span>${status.openGaps} open gap${status.openGaps === 1 ? '' : 's'}</span><span>Instructions ${status.instructionBytes}/${status.budgetBytes} bytes</span></p><details class="settings-more"><summary>Read new sessions</summary><p class="meta">Run <code>toolroll memory propose --repo ${repo}</code> on this computer.</p></details>`;
  const decide = (p: MemoryProposal, decision: 'accept' | 'reject', label: string) => postForm('/settings/knowledge/proposal', html`<button type="submit">${label}</button>`, { attrs: { class: 'inline' }, hidden: fields({ repo, proposal: p.id, decision }) });
  const cards = proposals.map(p => html`<details class="card proposal" open><summary><strong>${p.title}</strong> <span class="meta">#${p.id} · ${p.kind} · ${p.sessions} sessions</span></summary><p>${p.rationale}</p>${p.beforeText ? html`<pre class="knowledge-instructions">- ${p.beforeText}</pre>` : ''}${p.afterText ? html`<pre class="knowledge-instructions">+ ${p.afterText}</pre>` : ''}<ul class="memory-evidence">${p.evidence.map(ev => html`<li>“${ev.quote.slice(0, 200)}” <span class="meta">${ev.session.split(':')[0] ?? ''}</span></li>`)}</ul>${manage ? html`${decide(p, 'accept', 'Accept')} ${decide(p, 'reject', 'Reject')}` : ''}</details>`);
  return html`<section class="knowledge"><h2>Proposed from sessions</h2>${line}${cards.length ? cards : html`<p class="meta">Nothing to review. Suggestions appear when the same mistake shows up in two sessions.</p>`}</section>`;
}
