import { STALE_KNOWLEDGE, type KnowledgeDraft, type KnowledgeSelection, type KnowledgeView } from './project-knowledge.js';
const e = (s:unknown) => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const fields = (data:Record<string,unknown>) => Object.entries(data).map(([k,v])=>`<input type="hidden" name="${e(k)}" value="${e(v)}">`).join('');
export const KNOWLEDGE_CSS = `.knowledge{max-width:780px;min-width:0;overflow-wrap:anywhere}.knowledge .card{padding:20px;min-width:0;margin:16px 0}.knowledge h2{margin:0 0 12px}.knowledge form{display:grid;gap:12px;margin:0}.knowledge label{display:grid;gap:6px}.knowledge textarea,.knowledge input,.knowledge select{box-sizing:border-box;width:100%;min-width:0;max-width:100%}.knowledge textarea{resize:vertical;min-height:110px}.knowledge button,.knowledge summary,.knowledge .button-link{min-height:44px}.knowledge button{justify-self:start;white-space:nowrap}.knowledge summary{padding:12px 0;cursor:pointer}.knowledge pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}.knowledge .knowledge-actions{display:flex;gap:12px;flex-wrap:wrap}.knowledge .meta{font-size:.86rem}.knowledge .knowledge-source{display:block}.knowledge details+details{border-top:1px solid var(--so-line)}.memory-stats{display:flex;flex-wrap:wrap;gap:.4rem}.memory-stats span{padding:.15rem .55rem;border-radius:.375rem;background:var(--so-neutral-soft);color:var(--so-neutral-ink)}@media(max-width:600px){.knowledge .card{padding:16px}.knowledge h2{font-size:1.1rem}}`;
export function knowledgeHtml(view:KnowledgeView,csrf:string,canManage:boolean,draft?:KnowledgeDraft,error?:string):string {
  const manage=canManage && !!csrf;
  const base={csrf,repo:view.repo,identity:view.identity,revision:view.revision};
  const form=(action:string,body:string,extra:Record<string,unknown>={})=>`<form method="post" action="/settings/knowledge/change">${fields({...base,action,...extra})}${body}</form>`;
  const referenceFields=(d:KnowledgeDraft)=>`<label>Name<input name="title" maxlength="120" value="${e(d.title)}" required></label><label>Reference text<textarea name="content" rows="5" maxlength="12000">${e(d.content)}</textarea></label><details${d.path?' open':''}><summary>Use a project document</summary><label>Committed .md or .txt path<input name="path" value="${e(d.path)}" placeholder="docs/design-guide.md"></label><p class="meta">Uses the committed file instead of the text above. Save again to refresh it.</p></details><button type="submit">Save reference</button>`;
  const refs=view.knowledge.references.map(ref=>`<details class="card"${draft?.id===ref.id?' open':''}><summary><strong>${e(ref.title)}</strong></summary>${ref.path?`<span class="meta knowledge-source">${e(ref.path)} · ${e(ref.sourceRevision?.slice(0,7))}</span>`:''}<pre>${e(ref.content)}</pre>${manage?`<details${draft?.id===ref.id?' open':''}><summary>Edit reference</summary>${form('save',referenceFields(draft?.id===ref.id?draft:{title:ref.title,content:ref.path?'':ref.content,path:ref.path??''}),{id:ref.id})}<details><summary>Remove reference</summary>${form('remove','<p>Remove from future tasks. Previous run context stays available.</p><button>Remove reference</button>',{id:ref.id})}</details></details>`:''}</details>`).join('');
  const history=view.history.map(h=>`<li><a class="button-link" href="/settings/knowledge?repo=${encodeURIComponent(view.repo)}&version=${h.revision}">Version ${h.revision}</a> · ${e(h.actor)} · ${e(h.at.slice(0,16).replace('T',' '))} UTC</li>`).join('');
  if (view.stale) {
    // One notice, the saved knowledge on demand, one approver action. Editing waits until it is applied.
    const saved=view.stale.knowledge;
    const review=`<details><summary>Review saved knowledge</summary><pre class="knowledge-instructions">${e(saved.instructions||'No project instructions.')}</pre>${saved.references.map(ref=>`<details><summary>${e(ref.title)}</summary><pre>${e(ref.content)}</pre></details>`).join('')}</details>`;
    return `<section class="knowledge knowledge-library">${error?`<p class="problem" role="alert">${e(error)}</p>`:''}<section class="card knowledge-stale"><p role="status">${e(STALE_KNOWLEDGE)}.</p>${review}${manage?form('apply','<button>Apply saved knowledge</button>'):''}</section></section>`;
  }
  const instructions = `<pre class="knowledge-instructions">${e(view.knowledge.instructions||'No project instructions yet.')}</pre>`;
  const editor = manage ? `<details class="knowledge-editor"${draft?.instructions!==undefined?' open':''}><summary>${view.knowledge.instructions?'Edit instructions':'Add instructions'}</summary>${form('instructions',`<textarea aria-label="Project instructions" name="instructions" rows="5" maxlength="4000" placeholder="Goals, preferences, and what good work looks like…">${e(draft?.instructions??view.knowledge.instructions)}</textarea><button>Save instructions</button>`)}</details>` : '';
  return `<section class="knowledge knowledge-library">${error?`<p class="problem" role="alert">${e(error)}</p>`:''}<section class="knowledge-intro"><h2>Instructions</h2>${instructions}${editor}</section><section><h2>References</h2>${refs||'<p class="meta">Add a spec, design guide, or useful project document.</p>'}${manage?`<details class="card"${draft?.title&&!draft.id?' open':''}><summary>Add reference</summary>${form('save',referenceFields(draft?.id?{}:draft??{}))}</details>`:''}</section>${history?`<details><summary>Change history</summary><ol>${history}</ol></details>`:''}</section>`;
}
export function knowledgeContextHtml(snapshot:KnowledgeSelection|null):string {
  if (!snapshot) return '';
  return `<details class="knowledge result-knowledge"><summary>Context used</summary><p class="meta">Project knowledge · version ${snapshot.revision}${snapshot.inheritedFrom===null?'':` · from run #${snapshot.inheritedFrom}`}</p>${snapshot.instructions?`<details><summary>Instructions</summary><pre>${e(snapshot.instructions)}</pre></details>`:'<p>No project instructions were supplied.</p>'}${snapshot.references.map(r=>`<details><summary>${e(r.title)}</summary>${r.path?`<p class="meta">${e(r.path)} · ${e(r.sourceRevision)}</p>`:''}<pre>${e(r.content)}</pre></details>`).join('')}${snapshot.omitted.length?`<details><summary>Not included (${snapshot.omitted.length})</summary><ul>${snapshot.omitted.map(r=>`<li>${e(r.title)} — ${e(r.reason)}</li>`).join('')}</ul></details>`:''}</details>`;
}

// ---- project memory: decisions and search (2026-09-21) ----------------------------
import type { Decision, MemoryHit } from './project-memory.js';
export const MEMORY_INTRO = 'What the lead and crew read before they work. Every change keeps its history.';
export function decisionsHtml(repo: string, decisions: Decision[], csrf: string, canManage: boolean, draft?: { claim?: string; why?: string }, error?: string): string {
  const manage = canManage && !!csrf;
  const base = { csrf, repo };
  const form = (action: string, body: string, extra: Record<string, unknown> = {}) => `<form method="post" action="/settings/knowledge/decision">${fields({ ...base, action, ...extra })}${body}</form>`;
  const rows = decisions.map(d => `<details class="card decision" id="decision-${d.id}"><summary><strong>${e(d.claim)}</strong> <span class="meta">#${d.id} · ${e(d.decidedBy)} · ${e(d.decidedAt.slice(0, 10))}</span></summary><p>${e(d.why)}</p><p class="meta">${e(d.sourceKind)}${d.sourceRef ? ` · ${e(d.sourceRef)}` : ''}${d.supersedes === null ? '' : ` · replaces #${d.supersedes}`}</p>${manage ? form('retire', `<label>Why it no longer holds<input name="reason" maxlength="500" required></label><button type="submit">Retire</button>`, { decision: d.id }) : ''}</details>`).join('');
  const add = manage ? `<details class="knowledge-editor"${draft?.claim !== undefined ? ' open' : ''}><summary>Record a decision</summary>${form('record', `<label>The choice, in one sentence<input name="claim" maxlength="240" value="${e(draft?.claim)}" required></label><label>Why<textarea name="why" rows="3" maxlength="2000" required>${e(draft?.why)}</textarea></label><button type="submit">Record</button>`)}</details>` : '';
  return `<section class="knowledge"><h2>Decisions</h2>${error ? `<p class="problem" role="alert">${e(error)}</p>` : ''}${rows || '<p class="meta">No decisions yet. The lead suggests one when a conversation settles a choice.</p>'}${add}</section>`;
}
export function memorySearchHtml(repo: string, query: string, hits: MemoryHit[] | null): string {
  const kind = (h: MemoryHit) => h.kind === 'decision' ? `<a href="#decision-${e(h.ref)}">decision #${e(h.ref)}</a>` : h.kind === 'conversation' ? 'conversation' : h.kind;
  const results = hits === null ? '' : hits.length === 0 ? '<p class="meta">Nothing in project memory matches.</p>' : `<ul class="memory-hits">${hits.map(h => `<li><strong>${kind(h)}</strong> · ${e(h.title)}<br><span class="meta">${e(h.snippet)}</span></li>`).join('')}</ul>`;
  return `<section class="knowledge memory-search"><form method="get" action="/settings/knowledge"><input type="hidden" name="repo" value="${e(repo)}"><label>Search project memory<input name="memory" value="${e(query)}" maxlength="300" placeholder="Search decisions, references, lessons…" type="search" autocomplete="off"></label><button type="submit">Search</button></form>${results}</section>`;
}
import type { MemoryProposal } from './memory-pass.js';
export function proposalsHtml(repo: string, proposals: MemoryProposal[], status: { surface: string; instructionBytes: number; budgetBytes: number; sessions: { total: number; analyzed: number; failed: number }; openGaps: number; pending: number } | null, csrf: string, canManage: boolean): string {
  const manage = canManage && !!csrf;
  const line = status === null ? '' : `<p class="meta memory-stats"><span>${status.sessions.analyzed}/${status.sessions.total} sessions read${status.sessions.failed ? ` · ${status.sessions.failed} failed` : ''}</span><span>${status.openGaps} open gap${status.openGaps === 1 ? '' : 's'}</span><span>Instructions ${status.instructionBytes}/${status.budgetBytes} bytes</span></p>` +
    `<details class="settings-more"><summary>Read new sessions</summary><p class="meta">Run <code>toolroll memory propose --repo ${e(repo)}</code> on this computer.</p></details>`;
  const cards = proposals.map(p => `<details class="card proposal" open><summary><strong>${e(p.title)}</strong> <span class="meta">#${p.id} · ${e(p.kind)} · ${p.sessions} sessions</span></summary><p>${e(p.rationale)}</p>${p.beforeText ? `<pre class="knowledge-instructions">- ${e(p.beforeText)}</pre>` : ''}${p.afterText ? `<pre class="knowledge-instructions">+ ${e(p.afterText)}</pre>` : ''}<ul class="memory-evidence">${p.evidence.map(ev => `<li>“${e(ev.quote.slice(0, 200))}” <span class="meta">${e(ev.session.split(':')[0] ?? '')}</span></li>`).join('')}</ul>${manage ? `<form method="post" action="/settings/knowledge/proposal" class="inline">${fields({ csrf, repo, proposal: p.id, decision: 'accept' })}<button type="submit">Accept</button></form> <form method="post" action="/settings/knowledge/proposal" class="inline">${fields({ csrf, repo, proposal: p.id, decision: 'reject' })}<button type="submit">Reject</button></form>` : ''}</details>`).join('');
  return `<section class="knowledge"><h2>Proposed from sessions</h2>${line}${cards || '<p class="meta">Nothing to review. Suggestions appear when the same mistake shows up in two sessions.</p>'}</section>`;
}
