import { KNOWLEDGE_DESCRIPTORS } from "./knowledge-cli.js";
import { MEMORY_DESCRIPTORS } from "./memory-cli.js";
import { MODELS_DESCRIPTORS } from "./models-cli.js";
import { FLOWS_DESCRIPTORS } from "./flows-cli.js";
/**
 * The declared command guide (arc 5): the agent-facing surface as data,
 * dumped by `contract --commands`. This is DOCUMENTATION with a stable
 * shape, not authority — legacy verbs do not execute from it,
 * and the runtime envelope remains the truth. Its honest limits ride the
 * envelope itself as SURFACE_NOTES, because a source comment is invisible
 * to consumers (arc-5 review, finding 1).
 *
 * What the tests DO hold to the code: every root here is a routed verb
 * and every routed verb appears here; every declared flag lives in the
 * parser's global vocabulary with the declared arity; the subcommand
 * inventories for task/publish/config/approver/routine/contest match the
 * exported action lists their dispatchers consult; keyed mutations
 * declare --key; notableReasons come from DOCUMENTED_REASONS. What they
 * CANNOT prove — that a given flag is read by a given handler — is why
 * SURFACE_NOTES.flags says "intended".
 */

import { SESSION_DESCRIPTORS, type SessionDescriptor } from './session-contract.js';
import { sessionCliFlags } from './session-cli.js';
import { commandEntries, type CommandFlag, type CommandRow } from './contracts/cli.js';

/** A guide row and its flags are derived from their schemas in src/contracts/cli.ts. */
export type { CommandFlag, CommandRow };

/** The guide's limits, stated machine-readably in every dump. */
export const SURFACE_NOTES = {
  authority: "documentation is not permission; session descriptors also drive parser and request validation; legacy entries remain advisory",
  flags: "session flags are exact per operation; legacy flags are intended per command and may use a global parser vocabulary",
  reasons: "curated, not exhaustive — the runtime `reason` field is the truth; ignore tokens you do not recognize",
  database: "local database commands wait up to 15 seconds for another writer; an exhausted wait returns database-busy and names the selected file",
} as const;

export const SURFACE_SCHEMA_VERSION = 1;

const jsonFlag: CommandFlag = { name: "json", takesValue: false, meaning: "answer with one machine envelope on stdout" };
const keyFlag: CommandFlag = { name: "key", takesValue: true, meaning: "idempotency key — retry with the same key to get the first answer back" };
const dbFlag: CommandFlag = { name: "db", takesValue: true, meaning: "path to the database file (defaults to the installation's)" };
const repoFlag: CommandFlag = { name: "repo", takesValue: true, meaning: "which repository (repeatable where a command watches several)" };

const operator = (invocation: string, synopsis: string): CommandRow => ({
  invocation,
  synopsis,
  audience: "operator",
  agentMayInvoke: false,
  mutation: "unkeyed",
});
const operatorRead = (invocation: string, synopsis: string): CommandRow => ({
  invocation,
  synopsis,
  audience: "operator",
  agentMayInvoke: false,
  mutation: "none",
});

const GUIDE_ROWS: readonly CommandRow[] = [
  // ---- reports (reads) ----
  {
    invocation: "",
    envelopeCommand: "scan",
    synopsis: "report what is in flight (the no-verb default; scans below the working directory or the connected repositories)",
    audience: "agent",
    agentMayInvoke: true,
    mutation: "none",
    positionals: [{ name: "path", required: false, meaning: "directories to scan instead of the connected set" }],
    flags: [jsonFlag,
      { name: "all", takesValue: false, meaning: "ignore connected repos; scan everything discoverable" },
      { name: "local", takesValue: false, meaning: "branches only — no network" }],
  },
  { invocation: "pulls", synopsis: "report what is waiting on a person", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag] },
  { invocation: "graph", synopsis: "report which work graph is already here", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag] },
  { invocation: "repos", synopsis: "list connected repositories", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag] },
  operator("proposals", "what coordinators proposed over the MCP gateway — list, confirm <id> [--yes], dismiss <id>; confirming runs the plane's own door under your password"),
  operator("chat", "with a saved profile, --lead <id> --conversation <id> opens central chat; --say sends one message, --follow only reads updates, --authorize --terms-digest enables the displayed paid terms; --local uses the existing local coordinator, where --follow enables crew updates and --no-follow pauses them; proposals keep their approval requirements"),
  operator('connect', 'save an authenticated central HTTPS profile with --as and --token-stdin or --token-file; --local-login explicitly uses the existing private local sign-in; secrets never belong in arguments or URLs'),
  operatorRead('lead list', 'list central leads available to the signed-in account; --profile selects a saved connection'),
  operator('lead create', 'create a central lead with --name, --instructions and repeatable --project paths admitted by the server'),
  operator('lead update', 'change --name, --instructions or --status for --lead at --revision; projects remain fixed'),
  operator('lead member', 'set --account membership on --lead with --role, --active true|false and the current --revision'),
  operator('lead transfer', 'move ownership of --task to --lead at --revision; existing execution authority remains unchanged'),
  operatorRead('conversation list', 'list admitted conversations, optionally within --lead; attachment never starts model work'),
  operator('conversation create', 'create a conversation with --lead, --title, --visibility private|team and repeatable --project paths'),
  operatorRead('conversation show', 'read --conversation messages and saved work; no model call or read-marker mutation'),
  operator('conversation member', 'set --account membership on --conversation with --role, --active true|false and the current --revision; lead membership must already permit the role'),
  operator('conversation edit', 'edit your queued --message in --conversation at --revision using --text; running messages cannot be edited'),
  operator('conversation withdraw', 'withdraw your queued --message in --conversation at --revision; an active turn requires stop'),
  operator('conversation read', 'explicitly record your read position at --message within --conversation'),
  operator('conversation follow', 'enable or pause automatic lead summaries with --conversation and --enabled true|false, within the existing paid chat authorization; passive chat --follow only reads updates'),
  operator('conversation stop', 'request stopping the exact --message in --conversation; retain uncertain work until its owner settles it'),
  { invocation: "repos add", synopsis: "add a project: a Git repository, in the console at once; the lead adds with its token", audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent",
    positionals: [{ name: "path", required: false, meaning: "the repository (default: the one you are in)" }],
    flags: [jsonFlag, { name: "token", takesValue: true, meaning: "the lead token (or TOOLROLL_LEAD_TOKEN)" }],
    notableReasons: ["not-git", "unavailable", "refused", "locked"] },
  { invocation: "repos remove", synopsis: "remove a project from the console and the builder; its tasks and results stay saved", audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent",
    positionals: [{ name: "path", required: true, meaning: "the repository" }],
    flags: [jsonFlag, { name: "token", takesValue: true, meaning: "the lead token (or TOOLROLL_LEAD_TOKEN)" }],
    notableReasons: ["refused", "locked"] },
  operator("repos add-from-github", "preview, clone from GitHub, and connect - the console onboarding ceremony as a CLI verb"),
  { invocation: "contract", synopsis: "the machine contract: envelope version + capability tokens; --commands dumps this guide", audience: "agent", agentMayInvoke: true, mutation: "none",
    flags: [jsonFlag, { name: "commands", takesValue: false, meaning: "dump the declared command guide" }] },
  { invocation: "skills list", synopsis: "name the guides this exact binary serves", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag] },
  { invocation: "skills get", synopsis: "print one guide's markdown (raw on stdout; --json wraps it)", audience: "agent", agentMayInvoke: true, mutation: "none",
    positionals: [{ name: "name", required: true, meaning: "a guide name from `skills list`" }],
    flags: [jsonFlag], notableReasons: ["unknown-skill", "usage"] },
  {
    invocation: "skills install",
    synopsis: "install or refresh this binary's Toolroll guides for Claude Code; without --claude-code, write the repository-local Agent Skills entry",
    audience: "operator",
    agentMayInvoke: false,
    mutation: "identity-idempotent",
    flags: [jsonFlag,
      { name: "claude-code", takesValue: false, meaning: "install the user-level Claude Code skill" },
      { name: "dir", takesValue: true, meaning: "skill directory (default: ~/.claude/skills/toolroll)" },
      { name: "yes", takesValue: false, meaning: "write the previewed files" },
      { name: "repo", takesValue: true, meaning: "repository for the existing project-local install" },
      { name: "write-context", takesValue: false, meaning: "also add the managed AGENTS.md block for a project-local install" }],
    notableReasons: ["unconfirmed", "foreign-file", "usage"],
  },
  operator("link", "put toolroll on PATH"),
  operator("unlink", "take it off PATH"),
  operator("update", "update to the latest release: verified provenance, drained work, backup, rehearsal, health check, automatic restore; --rollback undoes it"),
  operator("demo", "a seeded throwaway sandbox"),
  { invocation: 'session capabilities', synopsis: 'Show executable session schemas and operator authority requirements; no credentials needed', audience: 'agent', agentMayInvoke: true, mutation: 'none', flags: [jsonFlag] },
  ...SESSION_DESCRIPTORS.map(spec => ({
    invocation: `session ${spec.operation}`, synopsis: spec.synopsis, audience: spec.audience, agentMayInvoke: spec.agentMayInvoke,
    mutation: spec.mutation ? 'keyed' as const : 'none' as const, inputSchema: spec.inputSchema,
    flags: Object.entries(sessionCliFlags(spec)).map(([name, arity]) => ({ name, takesValue: arity === 'value', meaning: name === 'key' ? 'keep the same key when reconciling; inspect after unknown delivery, never blind-retry' : `see session ${spec.operation} --help` })),
  })),

  ...KNOWLEDGE_DESCRIPTORS.map(spec => ({ invocation: `knowledge ${spec.action}`, synopsis: spec.synopsis, audience: "audience" in spec ? spec.audience : "agent" as const, agentMayInvoke: !("audience" in spec), mutation: spec.mutation, flags: spec.flags, ...(spec.takesQuery ? { positionals: [{ name: "query", required: true, meaning: "search text or source file for impact" }] } : {}) })),
  ...MEMORY_DESCRIPTORS.map(spec => ({ invocation: `memory ${spec.action}`, synopsis: spec.synopsis, audience: "agent" as const, agentMayInvoke: true, mutation: spec.mutation, flags: spec.flags, ...(spec.takesQuery ? { positionals: [{ name: "query", required: true, meaning: "search text, a decision id, or the decision sentence" }] } : {}) })),
  // Flow writes carry an approver's credential: an agent runs them only as the person asked, after showing the preview.
  ...FLOWS_DESCRIPTORS.map(spec => ({ invocation: `flows ${spec.action}`, synopsis: spec.synopsis, audience: "agent" as const, agentMayInvoke: true, mutation: spec.mutation, flags: spec.flags,
    ...("positionals" in spec ? { positionals: spec.positionals.map(name => ({ name, required: true, meaning: name === "flow" ? "a flow id from flows list" : "a trigger id from flows show, or for trigger add its settings as JSON, a JSON file, or -" })) } : {}) })),
  ...MODELS_DESCRIPTORS.map(spec => ({ invocation: `models ${spec.action}`, synopsis: spec.synopsis, audience: "agent" as const, agentMayInvoke: true, mutation: spec.mutation, flags: spec.flags, ...(spec.takesQuery ? { positionals: [{ name: "target", required: true, meaning: "the CLI to update, or on/off" }] } : {}) })),

  // ---- the queue (agent surface) ----
  { invocation: "status", synopsis: "running work, queued reasons, results to review, the latest release check and plan windows", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "integrations", synopsis: "every integration as Connected, Not set up or Broken, with its last success and error, what uses it and what to do; --saved skips new checks; never a secret", audience: "agent", agentMayInvoke: true, mutation: "none",
    flags: [jsonFlag, dbFlag, { name: "saved", takesValue: false, meaning: "show the last checks without checking again" }] },
  { invocation: "ready", synopsis: "what could be dispatched right now (rows carry reservedFor)", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "brief", synopsis: "with a saved central profile, --lead <id> --conversation <id> reads messages, proposals and saved work; --request-id inspects your saved receipt without resending; --local uses local DB catch-up, where --history selects the older operational report", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "gaps", synopsis: "requirement gaps blocking dispatch", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag, repoFlag] },
  { invocation: "grants", synopsis: "list authority grants", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "sync", synopsis: "refresh external-tracker mirrors and deliver write-backs — safe to run; fails closed", audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent",
    flags: [jsonFlag, dbFlag, repoFlag], notableReasons: ["no-op", "external"] },

  { invocation: "task add", synopsis: "queue work", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "title", required: true, meaning: "one line of what to do" }],
    flags: [jsonFlag, dbFlag, keyFlag,
      { name: "id", takesValue: true, meaning: "choose the task id" },
      { name: "repo", takesValue: true, meaning: "which repository the task belongs to" },
      { name: "report", takesValue: false, meaning: "a scout task: the deliverable is a report, never a branch" },
      { name: "replaces", takesValue: true, meaning: "the task this one replaces: it is cancelled and reads \"Replaced by <id>\"" },
      { name: "token", takesValue: true, meaning: "a lead token: filed as the lead, so it pings nobody" },
      { name: "checks", takesValue: true, meaning: "quick|full|off: this task's checks, overriding the project's level (\"skip the tests\" is off)" }],
    notableReasons: ["duplicate", "usage", "unknown-task", "unauthenticated"] },
  { invocation: "task ask", synopsis: "hand a task to a person: one message saying why, and the task is theirs", audience: "agent", agentMayInvoke: true, mutation: "unkeyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag,
      { name: "person", takesValue: true, meaning: "who to ask (someone who can see the task's project)" },
      { name: "why", takesValue: true, meaning: "what they need to do, one line" },
      { name: "token", takesValue: true, meaning: "the lead token (or TOOLROLL_LEAD_TOKEN)" }],
    notableReasons: ["unknown-task", "unknown-person", "unplaced", "unauthenticated"] },
  { invocation: "task checks", synopsis: "run checks on the task's latest result, on its exact commit, now; a pass upgrades its status and a failure stays visible",
    audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent",
    positionals: [{ name: "task", required: true, meaning: "any version of the task" }],
    flags: [jsonFlag, dbFlag, { name: "level", takesValue: true, meaning: "quick (default) or full" }],
    notableReasons: ["no-result", "no-check", "checks-failed"] },
  { invocation: "task add-tests", synopsis: "file a small task to write tests for the task's latest change; it waits for approval like any task",
    audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent",
    positionals: [{ name: "task", required: true, meaning: "any version of the task" }], flags: [jsonFlag, dbFlag],
    notableReasons: ["no-result"] },
  { invocation: "task list", synopsis: "a page of saved task status", audience: "agent", agentMayInvoke: true, mutation: "none",
    flags: [jsonFlag, dbFlag, { name: "state", takesValue: true, meaning: "queued|running|done|failed|cancelled" },
      { name: "view", takesValue: true, meaning: "all|needs-you|running|completed" },
      { name: "limit", takesValue: true, meaning: "page size, 1–100; default 40" },
      { name: "cursor", takesValue: true, meaning: "nextCursor from the previous response" },
      { name: "repo", takesValue: true, meaning: "filter to one project" }] },
  { invocation: "task show", synopsis: "one task in full", audience: "agent", agentMayInvoke: true, mutation: "none",
    positionals: [{ name: "id", required: true, meaning: "the task" }], flags: [jsonFlag, dbFlag], notableReasons: ["unknown-task"] },
  { invocation: "check-progress", synopsis: "current or final approved check progress", audience: "agent", agentMayInvoke: true, mutation: "none",
    positionals: [{ name: "run", required: true, meaning: "the build run" }], flags: [jsonFlag, dbFlag], notableReasons: ["unknown-run", "no-progress"] },
  { invocation: "task wait", synopsis: "wait for the current attempt to finish or need a person", audience: "agent", agentMayInvoke: true, mutation: "none",
    positionals: [{ name: "id", required: true, meaning: "the task" }], flags: [jsonFlag, dbFlag,
      { name: "timeout", takesValue: true, meaning: "stop waiting after this many seconds" }], notableReasons: ["unknown-task", "timeout", "failed", "needs-person"] },
  { invocation: "project show", synopsis: "show the saved local project and optional credential-file reference", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "project use", synopsis: "select an exact saved checkout; grants no project or execution authority", audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent",
    positionals: [{ name: "path", required: true, meaning: "exact saved project checkout path" }], flags: [jsonFlag, dbFlag, { name: "token-file", takesValue: true, meaning: "optional existing scoped coordinator credential file; saves only its path" }] },
  ...(['complete', 'revise'] as const).map(action => ({
    invocation: `task ${action}`, synopsis: action === 'complete' ? 'mark the exact inspected result complete; checks and permissions remain unchanged' : 'request a same-task revision using explicit feedback; existing approval terms apply',
    audience: 'agent' as const, agentMayInvoke: true, mutation: 'identity-idempotent' as const,
    positionals: [{ name: 'task', required: true, meaning: 'task or assignment id' }],
    flags: [jsonFlag, dbFlag,
      { name: 'token-env', takesValue: true, meaning: 'scoped coordinator credential environment variable' },
      { name: 'token-file', takesValue: true, meaning: 'scoped coordinator credential file; defaults to selected project reference' },
      ...(action === 'complete' ? [{ name: 'digest', takesValue: true, meaning: 'exact receipt from assignment show; required for JSON or scoped agents' },
        { name: 'pull-request', takesValue: false, meaning: "also open the result's pull request from that commit, as the console's Complete does; an approver's sign-in (--as/--token), never a scoped credential; refuses with pull-requests-off and the setup command" }]
        : [{ name: 'feedback', takesValue: true, meaning: 'specific requested change' }, { name: 'run', takesValue: true, meaning: 'exact result run; defaults to current result' }, { name: 'source', takesValue: true, meaning: 'exact scope digest; defaults to current terms' }, { name: 'key', takesValue: true, meaning: '32 hexadecimal characters for exact replay; defaults to a stable feedback identity' }]),
    ],
  })),
  { invocation: "task merge", synopsis: "merge the task's pull request once its checks pass — the console's Merge, behind the approver's password; the project's method (squash by default), branch deleted, recorded in the ledger",
    audience: "operator", agentMayInvoke: false, mutation: "identity-idempotent",
    positionals: [{ name: "task", required: true, meaning: "any version of the task" }],
    flags: [jsonFlag, dbFlag, { name: "as", takesValue: true, meaning: "the approver merging" }, { name: "token", takesValue: true, meaning: "their password" },
      { name: "anyway", takesValue: false, meaning: "merge a Quick or Off result without waiting for its full check" }],
    notableReasons: ["usage", "not-an-approver", "full-checks"] },
  ...(["show", "updates", "claim", "check", "brief", "inbox", "ack"] as const).map(action => ({
    invocation: `assignment ${action}`,
    synopsis: action === "show" ? "read the root, current work, owner and exact receipt"
      : action === "updates" ? "read durable updates after a cursor; save nextCursor after processing"
      : action === "claim" ? "record lead ownership; with the lead token the task reads \"<the lead's name> is on it\" and leaves Needs you until done, handed over, or 2 hours idle; grants no approval or execution authority"
      : action === "brief" ? "catch up from current assignments and project knowledge in the local database"
      : action === "inbox" ? "receive or replay a saved batch of lead status updates"
      : action === "ack" ? "acknowledge delivery of an inbox batch; leaves task completion unchanged"
      : "acknowledge the exact ready receipt as its lead; accepts no proof and deploys nothing",
    audience: "agent" as const, agentMayInvoke: true,
    mutation: action === "claim" || action === "check" || action === "inbox" || action === "ack" ? "identity-idempotent" as const : "none" as const,
    ...(["show", "claim", "check"].includes(action) ? { positionals: [{ name: "task", required: true, meaning: "any task in the assignment's existing correction chain" }] } : {}),
    flags: [jsonFlag, dbFlag,
      { name: "token-env", takesValue: true, meaning: "explicit environment variable containing a coordinator token; required for claim/check/inbox/ack unless token-file is used" },
      { name: "token-file", takesValue: true, meaning: "explicit coordinator token file; cannot be combined with token-env" },
      ...(action === "updates" ? [{ name: "after", takesValue: true, meaning: "last processed admitted update cursor; defaults to 0" }, { name: "limit", takesValue: true, meaning: "page size from 1 to 100; defaults to 50" }] : []),
      ...(action === "check" ? [{ name: "digest", takesValue: true, meaning: "exact current receipt digest from assignment show" }] : []),
      ...(action === "brief" ? [{ name: "repo", takesValue: true, meaning: "project to include within the credential's access" }, { name: "limit", takesValue: true, meaning: "assignment count from 1 to 25; defaults to 10" }] : []),
      ...(action === "inbox" || action === "ack" ? [{ name: "consumer", takesValue: true, meaning: "stable lowercase name for this lead's delivery cursor" }] : []),
      ...(action === "inbox" ? [{ name: "limit", takesValue: true, meaning: "batch size from 1 to 100; defaults to 10" }] : []),
      ...(action === "ack" ? [{ name: "batch", takesValue: true, meaning: "exact batch ID returned by assignment inbox" }] : []),
    ],
  })),
  operator("task state", "set a task's state by hand — an operator correction, not a workflow step (--replaced-by <id> with cancelled)"),
  operator("lead token", "mint the lead's credential behind your password (--revoke ends it): its own work pings nobody"),
  { invocation: "lead say", synopsis: "as the lead: one short message in its person's chat under the lead's name (Settings → Lead); several within two minutes are one message",
    audience: "agent", agentMayInvoke: true, mutation: "unkeyed",
    positionals: [{ name: "text", required: true, meaning: "one short line in plain words" }],
    flags: [jsonFlag, dbFlag,
      { name: "task", takesValue: true, meaning: "the task it is about" },
      { name: "token", takesValue: true, meaning: "the lead token (or TOOLROLL_LEAD_TOKEN)" }],
    notableReasons: ["usage", "unknown-task", "unauthenticated"] },
  { invocation: "task block", synopsis: "make one task wait for another", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the waiting task" }],
    flags: [jsonFlag, dbFlag, keyFlag, { name: "on", takesValue: true, meaning: "the blocker's id" }],
    notableReasons: ["unknown-task", "contest-open"] },
  { invocation: "task unblock", synopsis: "stop waiting", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the waiting task" }],
    flags: [jsonFlag, dbFlag, keyFlag, { name: "on", takesValue: true, meaning: "the blocker's id" }],
    notableReasons: ["unknown-task"] },
  { invocation: "task next", synopsis: "move a task to the front of ITS queue (scheduling only; approval still required)", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag, keyFlag, { name: "undo", takesValue: false, meaning: "back to filing order" }],
    notableReasons: ["unknown-task", "claimed", "contest-open"] },
    operator("task steer", "one credentialed note read before the task's next attempt — steering speaks with the operator's voice"),
  { invocation: "task assign", synopsis: "reserve a task for one worker, or return it to the shared queue", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag, keyFlag,
      { name: "runner", takesValue: true, meaning: "the worker to reserve for" },
      { name: "anyone", takesValue: false, meaning: "back to the shared queue" }],
    notableReasons: ["unknown-task", "claimed"] },
  { invocation: "task scope", synopsis: "state what success is; approval binds to this exact statement", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag, keyFlag,
      { name: "goal", takesValue: true, meaning: "what success is" },
      { name: "not", takesValue: true, meaning: "explicitly out of scope" },
      { name: "touches", takesValue: true, meaning: "comma-separated paths this may change" },
      { name: "budget-usd", takesValue: true, meaning: "spend ceiling for the build" },
      { name: "risk", takesValue: true, meaning: "declared risk: routine, elevated, or high — the route reads it" }],
    notableReasons: ["unknown-task", "contest-open"] },
  { invocation: "task plan", synopsis: "ask for a plan document (a planning session drafts; a person approves)", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag, keyFlag,
      { name: "provider", takesValue: true, meaning: "pin which provider plans THIS task (plan phase only)" },
      { name: "model", takesValue: true, meaning: "the pinned plan model, riding --provider" }],
    notableReasons: ["unknown-task"] },
  { invocation: "task hold", synopsis: "park a task with a reason", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag, keyFlag,
      { name: "reason", takesValue: true, meaning: "why it waits" },
      { name: "until", takesValue: true, meaning: "ISO time to resurface" }],
    notableReasons: ["unknown-task", "held"] },
  { invocation: "task unhold", synopsis: "release a hold", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag, keyFlag], notableReasons: ["unknown-task", "not-yours"] },
  { invocation: "task require", synopsis: "name the capabilities a task needs before dispatch", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag, keyFlag, { name: "require", takesValue: true, meaning: "comma-separated capability keys" }],
    notableReasons: ["unknown-task"] },
  operator("task approve", "the yes — nothing builds without one; binds to the scope digest"),
  operator("task requeue", "exit a stall: incidents resolved, strikes cleared, queued again"),
  operator("task regate", "explicitly rerun the approved check on the last exact commit — no agent or automatic retry"),
  { invocation: "task review", synopsis: "read a task's compact result packet with --brief, or a run's automatic findings without it", audience: "agent", agentMayInvoke: true, mutation: "none",
    positionals: [{ name: "id", required: true, meaning: "task id with --brief; run id otherwise" }],
    flags: [jsonFlag, dbFlag,
      { name: "brief", takesValue: false, meaning: "saved conclusion, changed files, checks, findings, screenshots, plan and next actions; missing fields say not recorded" },
      { name: "run", takesValue: true, meaning: "with --brief, select an exact finished attempt instead of the latest" },
      { name: "all", takesValue: false, meaning: "include LOW findings within the compact packet's limit; extra findings are counted" },
      { name: "token", takesValue: true, meaning: "the lead token (or TOOLROLL_LEAD_TOKEN)" }],
    notableReasons: ["usage", "unauthenticated", "not-found"] },
  operator("task accept", "record an explicit acceptance with limitations; does not change checks or prove deployment"),
  operator("task repair", "inspect or approve an existing historical repair draft; use task revise for new feedback"),
  operator("task route", "which configured agents plan, build and repair this task; phase and risk changes require renewed approval"),
  operator("task reopen", "resume external work its tracker closed and has been SEEN open again"),
  operator("task stop", "stop ONE exact live attempt (--run <id>): durable before any process is signalled, answers 'stopping' until its own processes are established gone; work, branch, and evidence preserved; no strike, no retry"),
  operator("run settle", "last resort for a finished run whose process witness can't be proven either way: records your --why in the ledger; refuses while any of the run's processes is alive"),
  operator("task resume", "resume the exact stopped attempt (--run <id>): refuses until it is quiescent, lifts only that stop's hold, approves nothing — the next pass re-proves the scope and inherits the draft with fresh proof"),

  // ---- leases (runner surface) ----
  { invocation: "claim", synopsis: "take one ready, approved task; answers with a lease", audience: "agent", agentMayInvoke: true, mutation: "keyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag, keyFlag,
      { name: "runner", takesValue: true, meaning: "your registered worker name" },
      { name: "token", takesValue: true, meaning: "the worker's token" },
      { name: "ttl", takesValue: true, meaning: "lease seconds" }],
    notableReasons: ["held", "fenced", "unapproved", "reserved", "external", "contest-open", "claimed", "not-ready"] },
  { invocation: "heartbeat", synopsis: "still working; extends the lease", audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent",
    positionals: [{ name: "lease", required: true, meaning: "the lease id" }],
    flags: [jsonFlag, dbFlag], notableReasons: ["not-leased", "fenced"] },
  { invocation: "release", synopsis: "done with it; fenced if superseded", audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent",
    positionals: [{ name: "lease", required: true, meaning: "the lease id" }],
    flags: [jsonFlag, dbFlag], notableReasons: ["not-leased", "fenced"] },
  { invocation: "reap", synopsis: "release every lease that ran out", audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent", flags: [jsonFlag, dbFlag] },
  { invocation: "tick", synopsis: "one unattended pass: claim, build in a leased worktree, commit to a branch — never pushes", audience: "agent", agentMayInvoke: true, mutation: "unkeyed",
    flags: [jsonFlag, dbFlag, repoFlag,
      { name: "runner", takesValue: true, meaning: "your registered worker name" },
      { name: "token", takesValue: true, meaning: "the worker's token" },
      { name: "max", takesValue: true, meaning: "tasks this pass (default 1)" },
      { name: "base", takesValue: true, meaning: "base ref for first attempts" }],
    notableReasons: ["empty", "fenced"] },
  { invocation: "build", synopsis: "build one claimed task directly (the piece tick automates)", audience: "agent", agentMayInvoke: true, mutation: "unkeyed",
    positionals: [{ name: "id", required: true, meaning: "the task" }],
    flags: [jsonFlag, dbFlag, repoFlag], notableReasons: ["not-leased", "unapproved"] },
  { invocation: "reconcile", synopsis: "recover what the last stretch left behind — safe to repeat", audience: "agent", agentMayInvoke: true, mutation: "identity-idempotent", flags: [jsonFlag, dbFlag, repoFlag] },

  // ---- reads over shared machinery ----
  { invocation: "runner list", synopsis: "registered workers", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "coordinator list", synopsis: "MCP filing credentials and their limits", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "approver list", synopsis: "who can say yes (names only)", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "cap list", synopsis: "recorded capabilities", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag, repoFlag] },
  { invocation: "outbox list", synopsis: "queued notifications", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "incident list", synopsis: "open incidents", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "routine list", synopsis: "scheduled routines", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "routine show", synopsis: "one routine in full", audience: "agent", agentMayInvoke: true, mutation: "none",
    positionals: [{ name: "id", required: true, meaning: "the routine" }], flags: [jsonFlag, dbFlag] },
  { invocation: "config show", synopsis: "phase and spend configuration", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag, repoFlag] },
  { invocation: "setup show", synopsis: "installation setup", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "verify show", synopsis: "the repository's check level, its approved full and quick commands, and a suggested quick command", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag, repoFlag] },
  { invocation: "intake show", synopsis: "intake configuration", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "providers", synopsis: "which agent providers this binary can drive, and their transports; --report records this machine's readiness under its runner", audience: "agent", agentMayInvoke: true, mutation: "none",
    flags: [jsonFlag,
      { name: "report", takesValue: false, meaning: "record readiness observations under --runner" },
      { name: "runner", takesValue: true, meaning: "the registered worker name reporting" },
      { name: "token", takesValue: true, meaning: "that worker's token" }] },
  { invocation: "template list", synopsis: "routine templates", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "template show", synopsis: "one template", audience: "agent", agentMayInvoke: true, mutation: "none",
    positionals: [{ name: "name", required: true, meaning: "the template" }], flags: [jsonFlag, dbFlag] },
  { invocation: "contest show", synopsis: "a tournament's state and results", audience: "agent", agentMayInvoke: true, mutation: "none",
    positionals: [{ name: "id", required: true, meaning: "the contest" }], flags: [jsonFlag, dbFlag] },
  { invocation: "webhook status", synopsis: "connected messaging services", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },
  { invocation: "publish status", synopsis: "publication and merge-grant state", audience: "agent", agentMayInvoke: true, mutation: "none", flags: [jsonFlag, dbFlag] },

  // ---- operator ceremonies and infrastructure (listed, detail-free) ----
  operator("approver add", "mint the credential that lets a person say yes"),
  operator("runner register", "register a worker bound to its repositories; its token is shown once"),
  operator("runner retire", "retire a worker"),
  operator("runner bind", "replace which repositories a worker may build in"),
  operator("runner capacity", "set how many tasks a worker runs at once; running work carries on, the new number applies at the next claim"),
  operator("project checks", "show or set a project's batch checks (--batch on|off, off by default): results that finish within 10 minutes share one full check on a temporary batch commit; nothing is merged into a real branch"),
  operator("project concurrency", "set how many of a project's tasks build at once (default 2, never past the worker's capacity); running work carries on"),
  operator("coordinator mint", "mint the MCP filing credential — repo-bound, rate-limited, token shown once"),
  operator("coordinator revoke", "revoke an MCP filing credential"),
  operator("mcp", "serve the MCP gateway over stdio — the coordinator credential is the only key it accepts"),
  operator("cap add", "record a capability"),
  operator("outbox deliver", "deliver queued notifications"),
  operator("peek", "watch live agents in the terminal — one pane per open run; --tmux opens a window per run"),
  operator("incident resolve", "resolve an incident"),
  operator("decide", "read and ANSWER parked decisions — answering is a person's act"),
  operator("routine add", "file a standing order"),
  operator("routine approve", "approve a standing order"),
  operator("routine refresh", "re-resolve the agents a standing order freezes from today's configuration — approves nothing; approve it again afterwards"),
  operator("routine pause", "pause a standing order"),
  operator("routine resume", "resume a standing order"),
  operator("routine run-now", "run a standing order immediately"),
  operatorRead("keys status", "which provider API keys are stored — never the values"),
  operator("keys set", "store a provider's API key as a private file — piped or --key-file, never on the command line"),
  operator("keys clear", "remove a stored provider key (kept only as a fallback; a subscription-mode provider is unaffected)"),
  operatorRead("keys verify", "check a stored key against its provider live — spends no tokens"),
  operator("keys auth", "choose subscription vs API key for a provider (subscription is the default; the key is kept as fallback)"),
  operatorRead("people list", "everyone who can sign in, their standing, and the open invites"),
  operator("people invite", "mint a single-use sign-in link for one person — their powers are pinned when you mint, never after"),
  operator("people projects", "set a person's project access — selected project, all projects, or no projects"),
  operator("people revoke", "end a person's access — their sessions, invites, and signed modes end with them; history stays"),
  operatorRead("mode show", "the repository's operating mode, in full — or 'locked' when none is signed"),
  operator("mode set", "sign a per-repository operating mode (password ceremony; standard or hands-off, always expiring)"),
  operator("publish merge", "say yes to ONE waiting merge — it fires only when CI is seen green on the exact commit you authorized"),
  operator("publish refire", "recover a merge whose issued call went silent — re-enters the full merge road, never auto-retried"),
  operatorRead("review show", "whether a project's finished builds get one automatic review"),
  operator("review on", "one automatic review of each finished build whose check passes; only HIGH findings send it back, once"),
  operator("review off", "finished builds go straight to the person, unreviewed"),
  operator("mode revoke", "revoke a repository's mode — one click, every act it covered falls back to its own ceremony"),
  operator("config set", "set phase or spend configuration"),
  operator("config clear", "clear phase or spend configuration"),
  operator("setup clear", "clear installation setup"),
  operator("verify set", "approve the one shell command the plane re-runs after every future commit (--quick \"<cmd>\" approves the fast check Quick runs); --self-heal binds one approved-setup replay when a required project executable is missing"),
  operator("verify clear", "revoke a repository's approved verification command; --level quick revokes only the quick command"),
  operator("verify level", "set a project's checks after each build: quick (the approved quick command), full, or off — an approver's act, in the ledger"),
  operator("intake grant", "grant an intake source"),
  operator("intake run", "run intake now"),
  operator("intake preview", "preview what intake would file"),
  operator("intake pr-comments", "intake review comments from a pull request"),
  operator("intake clear", "clear intake configuration"),
  operator("contest exclude", "exclude a contestant from a tournament"),
  operator("webhook primary", "choose which service receives alerts"),
  operator("webhook test", "send a test message"),
  operator("bridge", "the Telegram bridge (pairing, tokens, the follower)"),
  operator("enroll", "grant a repository authority (backends, dispatch) — its own explicit yes"),
  operator("revoke", "take an authority grant back"),
  operator("publish", "the publication pass: push built branches, open pull requests, sweep merges"),
  operator("publish grant", "grant publication or auto-merge authority"),
  operator("publish revoke", "take a publication grant back"),
  operator("publish unblock", "lift a repair's merge hold"),
  operator("publish rearm", "re-arm a refused merge after fixing the named cause"),
  operator("serve", "the operations console (HTTP)"),
  operator("watch", "the unattended loop, kept running"),
  operator("up", "console + worker + browser, one command"),
  operator("onboard", "add this repository, report signed-in agents, install or --remove the operator skill (--yes), offer the starter flows (--starter <ids>), and print the handoff"),
  operator("daemon", "install the loop under the OS service manager"),
];

/** Every declared command, in guide order, paired with the schema of its `--json` answer (src/contracts/cli.ts). */
export const COMMAND_ENTRIES = commandEntries(GUIDE_ROWS);

/** The guide `contract --commands` dumps: each declared command's row, projected from COMMAND_ENTRIES. */
export const COMMAND_GUIDE: readonly CommandRow[] = COMMAND_ENTRIES.map(entry => entry.guide);
